services:
  - type: web
    name: novatech-store-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /api/health
    preDeployCommand: alembic upgrade head && novatech-import-products seed/products.json
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: COOKIE_SECURE
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: novatech-store-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: novatech-store-redis
          property: connectionString
      - key: APP_ORIGIN
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
      - key: OTP_SECRET
        generateValue: true
      - key: MFA_ENCRYPTION_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: S3_ENDPOINT_URL
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: ASSET_ORIGIN
        sync: false

  - type: worker
    name: novatech-store-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    startCommand: python -m app.worker
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: novatech-store-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: novatech-store-redis
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
      - key: OTP_SECRET
        generateValue: true
      - key: EMAIL_FROM
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false

  - type: keyvalue
    name: novatech-store-redis
    plan: starter
    ipAllowList: []
    maxmemoryPolicy: noeviction
    persistenceMode: journal-snapshot

databases:
  - name: novatech-store-db
    plan: basic-256mb
    databaseName: novatech
    user: novatech
